### PR TITLE
Test lstate and evidence in consensus

### PR DESCRIPTION
**Pull request by kosegor**
## Scope
add coverage to `lstate` package
remove unneeded code
fix mpk submission ShouldRetry function

## Why?
Improve code robustness

### CODE REVIEW

**Comment by vtleonardo** [comment]
Please, remove `|/consensus` from https://github.com/MadBase/MadNet/blob/candidate/.github/workflows/ci.yml#L153 and see if the golang unit test on CI will execute the new tests and if they will pass.

**Comment by kosegor** [comment]
> Please, remove `|/consensus` from https://github.com/MadBase/MadNet/blob/candidate/.github/workflows/ci.yml#L153 and see if the golang unit test on CI will execute the new tests and if they will pass.

Hey @vtleonardo there is one tests that is failing in the dman package. This package is addressed in a ticket is assigned to Ricardo. All my tests are passing.

**Comment by vtleonardo** [comment]
> > Please, remove `|/consensus` from https://github.com/MadBase/MadNet/blob/candidate/.github/workflows/ci.yml#L153 and see if the golang unit test on CI will execute the new tests and if they will pass.
> 
> Hey @vtleonardo there is one tests that is failing in the dman package. This package is addressed in a ticket is assigned to Ricardo. All my tests are passing.

Can you blacklist `/consensus/dman|` only dman for now?

**Comment by kosegor** [comment]
> 

Done, all tests pass!

**Pull request merged**
